--========================================
-- EMERSON Weekly Forecast Overall Results
-- Model-level WMAPE and BIAS
--========================================

SELECT
    'SEASONAL' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(SEASONAL_FORECAST)) AS FORECAST,
    ROUND(SUM(SEASONAL_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(SEASONAL_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(SEASONAL_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA

UNION ALL

SELECT
    'ARIMA' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(ARIMA_FORECAST)) AS FORECAST,
    ROUND(SUM(ARIMA_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(ARIMA_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(ARIMA_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA

UNION ALL

SELECT
    'XGBOOST' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(XGBOOST_FORECAST)) AS FORECAST,
    ROUND(SUM(XGBOOST_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(XGBOOST_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(XGBOOST_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA

UNION ALL

SELECT
    'MA' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(MA_FORECAST)) AS FORECAST,
    ROUND(SUM(MA_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(MA_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(MA_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA

UNION ALL

SELECT
    'BLENDED' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(BLENDED_FORECAST)) AS FORECAST,
    ROUND(SUM(BLENDED_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(BLENDED_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(BLENDED_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA

UNION ALL

SELECT
    'DEMANTRA' AS MODEL,
    SUM(HISTORY) AS HISTORY,
    ROUND(SUM(DEMANTRA_FORECAST)) AS FORECAST,
    ROUND(SUM(DEMANTRA_ERROR)) AS ABS_ERROR,
    ROUND(ROUND((SUM(DEMANTRA_ERROR) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS WMAPE,
    ROUND(ROUND(((SUM(HISTORY) - SUM(DEMANTRA_FORECAST)) / NULLIF(SUM(HISTORY), 0))::NUMERIC, 4) * 100, 2) AS BIAS
FROM FORECAST_DATA;
